### ISSUE TITLE
Model files load: failure

### ISSUE THREAD

**Issue by Tolkinz** [aburahamu/ComfyUI-IsNiceParts#3]
I downloaded yolox_l.onnx from huggingface, made a 'models' sub-folder under [IsNiceParts] folder.
It still gives me the following error message in terminal.
I looked it closely and found that 'slash' direction is reversed. My folder should look like .../.../.../... but this error message all of a sudden saying reverse-slash at the end. So, there must be a script telling the module about the location to look for models, I want to check that script and want to put correct slash there, but couldn't find where to look.
Can you help me please? Which file contains such information about the path of model files?

ComfyUI/custom_nodes/ComfyUI-IsNiceParts/models\yolox_l.onnx failed. File doesn't exist

* Macos, M3Max.

**Comment by aburahamu** [comment]
dwpose
/wholebody.pyの20行目と22行目にモデルファイルのパスを書き込んであります。そこのバックスラッシュを「/」に直すと上手くいくかもしれません。

**Comment by Tolkinz** [comment]
ComfyUI/custom_nodes/tri3d-comfyui-nodes/dwpose/wholebody.py

Thanks for the comment! Is the above path correct? Line 20 is the first line of self.session..............., I do not see model path.... I see another wholebody.py under src, which doesn't look like it. 

class Wholebody:
    def __init__(self, onnx_det: str, onnx_pose: str):
        # Always loads to CPU to avoid building OpenCV.
        device = 'cpu'
        backend = cv2.dnn.DNN_BACKEND_OPENCV if device == 'cpu' else cv2.dnn.DNN_BACKEND_CUDA
        # You need to manually build OpenCV through cmake to work with your GPU.
        providers = cv2.dnn.DNN_TARGET_CPU if device == 'cpu' else cv2.dnn.DNN_TARGET_CUDA

        self.session_det = cv2.dnn.readNetFromONNX(onnx_det)
        self.session_det.setPreferableBackend(backend)
        self.session_det.setPreferableTarget(providers)

        self.session_pose = cv2.dnn.readNetFromONNX(onnx_pose)
        self.session_pose.setPreferableBackend(backend)
        self.session_pose.setPreferableTarget(providers)



---------------------------

ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_controlnet_aux/dwpose/wholebody.py

class Wholebody:
    def __init__(self, det_model_path: Optional[str] = None, pose_model_path: Optional[str] = None, torchscript_device="cuda"):
        self.det_filename = det_model_path and os.path.basename(det_model_path)                         <--- this is line 20
        self.pose_filename = pose_model_path and os.path.basename(pose_model_path)
        self.det, self.pose = None, None
        # return type: None ort cv2 torchscript
        self.det_model_type = get_model_type("DWPose",self.det_filename)
        self.pose_model_type = get_model_type("DWPose",self.pose_filename)
        # Always loads to CPU to avoid building OpenCV.
        cv2_device = 'cpu'
        cv2_backend = cv2.dnn.DNN_BACKEND_OPENCV if cv2_device == 'cpu' else cv2.dnn.DNN_BACKEND_CUDA
        # You need to manually build OpenCV through cmake to work with your GPU.
        cv2_providers = cv2.dnn.DNN_TARGET_CPU if cv2_device == 'cpu' else cv2.dnn.DNN_TARGET_CUDA
        ort_providers = get_ort_providers()

**Comment by aburahamu** [comment]
ここです。
![image](https://github.com/user-attachments/assets/2b5801f8-7d0c-470b-8f96-ff8935d7b729)

**Comment by Tolkinz** [comment]
Thank you so much! 
I couldn't find it because when model load was failed, I uninstalled and forgot it.... damn it.
Reinstalled and found the file you mentioned, it was there. 
It now loads smoothly!!! 

👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻

**Comment by aburahamu** [comment]
うまくいって良かったです。
Congratulations.　:)
